name: time-script
version: 0.1.0.0
category: Simple
license: MIT
author: aiya000
copyright: 2018- aiya000
maintainer: aiya000.develop@gmail.com
github: aiya000/hs-time-script

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Werror

default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - DuplicateRecordFields
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadFailDesugaring
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

dependencies:
  - base >= 4.7 && < 5
  - rio
  - tonatona
  - tonatona-logger

library:
  source-dirs:
    - src

executables:
  tims:
    source-dirs:
      - app
    main: Main.hs
    dependencies:
      - time-script

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - time-script
      - hspec
      - QuickCheck
  doctest:
    main: DocTest.hs
    source-dirs:
      - test
    dependencies:
      - time-script
      - doctest
      - Glob
