resolver: lts-14.15
packages:
  - '.'
extra-deps:
  - git: https://github.com/tonatona-project/tonatona
    commit: 224e084fef661873808eaf3f70bb7887ff8b50e8
    subdirs:
      - tonaparser
      - tonatona
      - tonatona-logger
      - tonatona-persistent-postgresql
      - tonatona-persistent-sqlite
      - tonatona-servant
  - git: https://github.com/aiya000/hs-character-cases
    commit: e4561b8e849f8d487b82389d7177142786f1a9f8
flags: {}
extra-package-dbs: []
